language: node_js
node_js:
- '7'
deploy:
  provider: npm
  email: integration-dev@thomascookonline.com
  api_key:
    secure: SCC9Rnm9wWwkSbQUUGsp6ArPGA8ASjubdg4bQQvUJxA69f+WRKJAK7Bq/FnrajZNMeMWYUATsRJb0gLkth2EJUj0wpIXXdp6eqltItMJfL6Rqi/pCRRuy1KrcQn9qwUg6pV0rIyU+kh4nZFD5Dvvrs0HFfjcijZ+EFQB+qz4qDbShzY770Gsi496n4daBKyZe0iwc+N45dnrHCZ0EgE1iBfwEmv/IUuSRJo+jZEQfGFZTGdWvytncAmTx4Fjhz488t9lRfSh7snh57LcnH4aBRhZoolZd92x27dfvGrB56JsLpTr4YTAMDSxx/AKTpH3dYVvek+NKPPE84re51jBzZ6RpDo0YHC1DJTCTu78Bf0GNvFZSLQM/NQI2cfHcaFe4pQ85BHof5tqpbmadoG9sxD2sahzoRmKh0JarDrfPFACfHk00gm/UmKS8deqBGT8yeX+/mJSgVejk1Xpe5oUzl7Orz750BKnFIMTTTBM1YcNplAdkDklbkwjBoionThQ/oUeoNG9zR21yZUqdg/8bwLwOXd11d1LuMxC74ySAgNQ60gwfGTqSOYHojojOBYbv7p5RDk3PWQ9krnNy+W0qoOcKHeJjWYQ+lBfyP8pLHrIJ1RNShDB8DlgNmgLpQvKw27FD4RR/MkJn26gmzEvcEMAaWddMGE/qTHKyiC5N5E=
  on:
    tags: true
    repo: tcdl/bunyan-encoder
    node: '7'
